package pipeline

import (
	"fmt"
	"strings"
)

// Exporter converts a PersonaProfile into a markdown persona file.
// The output is designed to be used directly as a system prompt.
type Exporter struct{}

func NewExporter() *Exporter { return &Exporter{} }

// ToMarkdown generates a rich, usable persona markdown file.
func (e *Exporter) ToMarkdown(profile *PersonaProfile) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s — AI Persona\n\n", profile.Name))
	b.WriteString("> **Disclaimer:** This is an AI-generated persona approximation built from publicly available sources. ")
	b.WriteString("It is not affiliated with, endorsed by, or representative of the real person. ")
	b.WriteString("Use responsibly.\n\n")
	b.WriteString("---\n\n")

	// System prompt block — the key deliverable
	b.WriteString("## System Prompt\n\n")
	if profile.LLMEnriched {
		b.WriteString("_AI-synthesized from your sources. Copy into any AI assistant to activate the persona:_\n\n")
	} else {
		b.WriteString("_Copy this into any AI assistant to activate the persona:_\n\n")
	}
	b.WriteString("```\n")
	if profile.LLMEnriched && profile.LLMSystemPrompt != "" {
		b.WriteString(profile.LLMSystemPrompt)
	} else {
		b.WriteString(e.buildSystemPrompt(profile))
	}
	b.WriteString("\n```\n\n")
	b.WriteString("---\n\n")

	// Summary
	b.WriteString("## Persona Summary\n\n")
	b.WriteString(profile.Summary + "\n\n")

	// Voice guide (LLM only)
	if profile.LLMEnriched && profile.VoiceGuide != "" {
		b.WriteString("## Voice Guide\n\n")
		b.WriteString("_How they actually sound — use this to calibrate the persona:_\n\n")
		b.WriteString(profile.VoiceGuide + "\n\n")
	}

	// Personality dimensions
	b.WriteString("## Personality Dimensions\n\n")
	dimOrder := []string{"humor", "tone", "opinions", "emotion"}
	for _, key := range dimOrder {
		if dim, ok := profile.Dimensions[key]; ok {
			bar := confidenceBar(dim.Score)
			b.WriteString(fmt.Sprintf("### %s %s %.0f%%\n", dim.Name, bar, dim.Score*100))
			b.WriteString(dim.Description + "\n\n")
			if len(dim.Evidence) > 0 {
				b.WriteString("**Evidence from sources:**\n")
				for _, ev := range dim.Evidence {
					b.WriteString(fmt.Sprintf("> %s\n\n", ev))
				}
			}
		}
	}

	// Communication style
	b.WriteString("## Communication Style\n\n")
	style := profile.VocabStyle
	b.WriteString(fmt.Sprintf("- **Sentence length:** %s\n", style.SentenceStyle))
	b.WriteString(fmt.Sprintf("- **Formality:** %.0f%% formal\n", style.Formality*100))
	b.WriteString(fmt.Sprintf("- **Verbosity:** %.0f%%\n", style.Verbosity*100))
	if len(style.CommonWords) > 0 {
		b.WriteString(fmt.Sprintf("- **Characteristic vocabulary:** %s\n", strings.Join(style.CommonWords, ", ")))
	}
	b.WriteString("\n")

	// Interests
	if len(profile.Interests) > 0 {
		b.WriteString("## Key Interests & Topics\n\n")
		for _, interest := range profile.Interests {
			b.WriteString(fmt.Sprintf("- %s\n", interest))
		}
		b.WriteString("\n")
	}

	// Lifestyle section (behavioral signals — silently inform persona)
	hasLifestyle := len(profile.Locations) > 0 || len(profile.Foods) > 0
	if hasLifestyle {
		b.WriteString("## Lifestyle & Habits\n\n")
		b.WriteString("_Inferred from behavioral signals — not direct statements._\n\n")
		if len(profile.Locations) > 0 {
			b.WriteString(fmt.Sprintf("- **Places:** %s\n", strings.Join(profile.Locations, ", ")))
		}
		if len(profile.Foods) > 0 {
			b.WriteString(fmt.Sprintf("- **Food/Dining:** %s\n", strings.Join(profile.Foods, ", ")))
		}
		b.WriteString("\n")
	}

	// Core beliefs
	if len(profile.CoreBeliefs) > 0 {
		b.WriteString("## Core Beliefs & Opinions\n\n")
		for _, belief := range profile.CoreBeliefs {
			b.WriteString(fmt.Sprintf("> %s\n\n", belief))
		}
	}

	// Quirks
	if len(profile.Quirks) > 0 {
		b.WriteString("## Distinctive Quirks\n\n")
		for _, q := range profile.Quirks {
			b.WriteString(fmt.Sprintf("- %s\n", q))
		}
		b.WriteString("\n")
	}

	// Sample phrases
	if len(profile.SamplePhrases) > 0 {
		b.WriteString("## Sample Phrases\n\n")
		b.WriteString("_Representative sentences from the sources:_\n\n")
		for _, phrase := range profile.SamplePhrases {
			b.WriteString(fmt.Sprintf("> %s\n\n", phrase))
		}
	}

	// Usage instructions
	b.WriteString("---\n\n")
	b.WriteString("## How to Use This Persona\n\n")
	b.WriteString("1. **ChatGPT / Claude / Gemini:** Copy the System Prompt above into the system instructions field\n")
	b.WriteString("2. **Custom agents:** Use this file as the agent's system prompt\n")
	b.WriteString("3. **OpenClaw:** Save this file as `<name>.md` in your workspace and reference it in agent config\n\n")
	b.WriteString(fmt.Sprintf("_Generated by Mirra · %s persona · Not affiliated with the real person_\n", profile.Name))

	return b.String()
}

func (e *Exporter) buildSystemPrompt(p *PersonaProfile) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("You are roleplaying as %s. ", p.Name))
	b.WriteString("This is a fictional AI persona built from public information — you are NOT the real person.\n\n")

	b.WriteString("## Your Personality\n")
	b.WriteString(p.Summary + "\n\n")

	b.WriteString("## How You Communicate\n")
	style := p.VocabStyle
	b.WriteString(fmt.Sprintf("- Use %s sentences\n", style.SentenceStyle))
	if style.Formality < 0.4 {
		b.WriteString("- Keep it casual and conversational\n")
	} else if style.Formality > 0.6 {
		b.WriteString("- Maintain a formal, structured tone\n")
	} else {
		b.WriteString("- Balance professionalism with warmth\n")
	}

	humor := p.Dimensions["humor"]
	if humor.Score > 0.5 {
		b.WriteString("- Incorporate humor and wit naturally\n")
	}

	opinions := p.Dimensions["opinions"]
	if opinions.Score > 0.5 {
		b.WriteString("- Don't shy away from sharing opinions directly\n")
	}

	if len(style.CommonWords) > 0 {
		b.WriteString(fmt.Sprintf("- Your characteristic vocabulary includes: %s\n", strings.Join(style.CommonWords[:min2(5, len(style.CommonWords))], ", ")))
	}

	if len(p.Interests) > 0 {
		b.WriteString(fmt.Sprintf("\n## Your Core Interests\n%s\n", strings.Join(p.Interests, ", ")))
	}

	if len(p.Quirks) > 0 {
		b.WriteString("\n## Your Quirks\n")
		for _, q := range p.Quirks {
			b.WriteString(fmt.Sprintf("- %s\n", q))
		}
	}

	if len(p.SamplePhrases) > 0 {
		b.WriteString("\n## Examples of How You Talk\n")
		for _, phrase := range p.SamplePhrases {
			b.WriteString(fmt.Sprintf("- \"%s\"\n", phrase))
		}
	}

	b.WriteString("\n## Important Rules\n")
	b.WriteString("- Stay in character at all times\n")
	b.WriteString("- Never claim to be the real person or have their actual memories\n")
	b.WriteString("- If asked about sensitive topics the real person hasn't addressed publicly, say you'd rather not speculate\n")
	b.WriteString("- Be helpful and engaging while maintaining the persona's voice\n")

	return b.String()
}

func confidenceBar(score float64) string {
	filled := int(score * 5)
	bar := strings.Repeat("█", filled) + strings.Repeat("░", 5-filled)
	return fmt.Sprintf("[%s]", bar)
}
